---
- name: Install Java
  hosts: app_server
  become: yes
  become_user: automated
  roles:
    - geerlingguy.java

- name: Download Application from Repo
  hosts: app_server
  become_user: automated
  become: yes
  tasks:
    - get_url: 
        force: yes
        url: "{{ ARTIFACT_URL }}"
        dest: "/tmp/petclinic.war"
    - stat: 
        path: "/tmp/petclinic.war"
        
- name: copying the war file into tomcat server
  hosts: app_server
  become_user: automated
  become: yes
  tasks:
    - name: copy
      copy:
       src: "/tmp/petclinic.war"
       dest: "/opt/tomcat/webapps/petclinic.war"
       remote_src: yes
       owner: tomcat
       group: tomcat
       mode: 0644
 
#- name: Setup Spring Boot
#  hosts: app_server
#  become: yes
#  become_user: root
#  roles: 
#    - { role: pellepelster.springboot-role,
#        spring_boot_file: "petclinic.war",
#        spring_boot_file_source: "/tmp/petclinic.war",
#        spring_boot_application_id: "petclinic"
#    } 
